### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by RobbieTheWagner** [lolmaus/ember-stamplay#1]
Wondering if this is still being worked on or if you recommend something else instead?

**Comment by lolmaus** [comment]
Hey @rwwagner90. I'm sorry, I was on a vacation and mail piled up.

I am not actively working on this addon, but I'm not planning to abandon it either.

Would you like to join efforts?

**Comment by RobbieTheWagner** [comment]
No worries @lolmaus. I haven't looked into the code yet, but I would potentially be interested in working on it.

**Comment by lolmaus** [comment]
Do you have a specific Stamplay-based app in mind that you wanna leverage Ember for? Or would you like to start a practice app that we could develop together?

**Comment by RobbieTheWagner** [comment]
All I currently use Stamplay for is updating my star counts here http://shipshape.io/open-source , but I plan to use it for a contact form as well.
